// --- 多语言排序变量 ---
const speedOrder_cn = ['充能', '魔法', '冥河', '飞速', '舞者', '快速', '潮汐', '中等', '杀手', '慢', '非常慢'];
const speedOrder_tc = ['充能', '魔法', '冥河', '飛速', '舞者', '快速', '潮汐', '中等', '殺手', '慢速', '非常慢'];
const speedOrder_en = ['Charge', 'Magic', 'Styx', 'Very Fast', 'Dancer', 'Fast', 'Changing Tides', 'Average', 'Slayer', 'Slow', 'Very Slow'];
const colorOrder_cn = ['红', '绿', '蓝', '黄', '紫'];
const colorOrder_tc = ['紅', '綠', '藍', '黃', '紫'];
const colorOrder_en = ['Red', 'Green', 'Blue', 'Yellow', 'Purple'];


// --- 技能类型翻译映射表 ---
const skillTypeTranslations_cn = {
    "Buffers (ATK)": "攻击增益", "Buffers (DEF)": "防御增益", "Debuffers (ATK)": "攻击减益", "Debuffers (DEF)": "防御减益",
    "Stacks Removers": "叠加移除", "Stacking Heroes": "叠加", "Extra Damage Dealers": "额外伤害", "DoT Attackers": "持续伤害",
    "Dispellers": "驱散", "Cleansers": "净化", "Buff Stealers": "增益窃取者", "Buff Blockers": "增益格挡者",
    "Cleanse Blockers": "净化格挡者", "Status Effects Blockers": "状态效果格挡", "Effect Duration Resetters": "效果持续重置",
    "Dancers": "舞者", "Healers": "治疗", "Healers (Special)": "特殊治疗", "Heal over Time (HoT)": "持续治疗",
    "Health Boosters": "生命强化", "Max Health Reducers": "最大生命削减", "Healing Reducers": "治疗削减", "Revivers": "复活",
    "Resurrection Inhibitors": "复活抑制", "Random Position": "重排队伍", "Mana Raisers": "法力提升", "Mana Generation Buffers": "法力生成增益",
    "Mana Reducers or Blockers": "法力削减或格挡", "Mana Corruption": "法力腐败", "Mindless Attack & Mindless Heal": "精神错乱攻击&治疗",
    "Silencers": "沉默", "Sleepweavers": "沉睡", "Taunters": "嘲讽", "Damage Sharers": "伤害分摊", "Damage Reducers": "伤害减免",
    "Dodgers": "闪避", "Ghost Form & Hiding": "鬼魂形态与隐藏", "Immunity Providers": "提供免疫", "Minions Summoners": "召唤小兵",
    "Mega Minions Summoners": "召唤巨型小兵", "Minions Counters": "反制小兵", "Minions Boosters": "小兵强化", "Fiends Summoners": "召唤恶魔",
    "Fiends Counters": "反制恶魔", "Counterattackers": "反击", "Reflectors": "反射", "Bypassers": "绕过", "Targeting Type": "目标类型",
    "Snipers": "狙击手", "AoE Attackers (Hit-5)": "全体攻击 (打5)", "AoE Attackers (Hit-3)": "范围攻击 (打3)",
    "Chain & Random Attackers": "连锁与随机攻击", "Board Alterers": "改变面板", "Ability Scores Modifiers": "属性修改",
    "Negative Effects On Self Or Allies": "对自身或友军负面效果", "Status Effect Conversion": "状态效果转换"
};
const skillTypeTranslations_tc = {
    "Buffers (ATK)": "攻擊增益", "Buffers (DEF)": "防禦增益", "Debuffers (ATK)": "攻擊減益", "Debuffers (DEF)": "防禦減益",
    "Stacks Removers": "疊加移除", "Stacking Heroes": "疊加", "Extra Damage Dealers": "額外傷害", "DoT Attackers": "持續傷害",
    "Dispellers": "驅散", "Cleansers": "凈化", "Buff Stealers": "增益竊取者", "Buff Blockers": "增益格擋者",
    "Cleanse Blockers": "凈化格擋者", "Status Effects Blockers": "狀態效果格擋", "Effect Duration Resetters": "效果持續重置",
    "Dancers": "舞者", "Healers": "治療", "Healers (Special)": "特殊治療", "Heal over Time (HoT)": "持續治療",
    "Health Boosters": "生命強化", "Max Health Reducers": "最大生命削減", "Healing Reducers": "治療削減", "Revivers": "復活",
    "Resurrection Inhibitors": "復活抑製", "Random Position": "重排隊伍", "Mana Raisers": "法力提升", "Mana Generation Buffers": "法力生成增益",
    "Mana Reducers or Blockers": "法力削減或格擋", "Mana Corruption": "法力腐敗", "Mindless Attack & Mindless Heal": "精神錯亂攻擊&治療",
    "Silencers": "沈默", "Sleepweavers": "沈睡", "Taunters": "嘲諷", "Damage Sharers": "傷害分攤", "Damage Reducers": "傷害減免",
    "Dodgers": "閃避", "Ghost Form & Hiding": "鬼魂形態與隱藏", "Immunity Providers": "提供免疫", "Minions Summoners": "召喚小兵",
    "Mega Minions Summoners": "召喚巨型小兵", "Minions Counters": "反製小兵", "Minions Boosters": "小兵強化", "Fiends Summoners": "召喚惡魔",
    "Fiends Counters": "反製惡魔", "Counterattackers": "反擊", "Reflectors": "反射", "Bypassers": "繞過", "Targeting Type": "目標類型",
    "Snipers": "狙擊手", "AoE Attackers (Hit-5)": "全體攻擊 (打5)", "AoE Attackers (Hit-3)": "範圍攻擊 (打3)",
    "Chain & Random Attackers": "連鎖與隨機攻擊", "Board Alterers": "改變面板", "Ability Scores Modifiers": "屬性修改",
    "Negative Effects On Self Or Allies": "對自身或友軍負面效果", "Status Effect Conversion": "狀態效果轉換"
};

// --- 语言文本管理 ---
const i18n = {
    cn: {
        metaDescription: "Heroplan是为《帝国与谜题》(Empires & Puzzles)玩家打造的终极英雄资料库。快速查询和比较所有英雄的详细数据、特殊技能、家族加成和攻略信息。",
        seoHeading: "《帝国与谜题》一站式英雄资料库与玩家工具箱",
        seoPara1: "欢迎使用由 <strong>Heroplan.io</strong> 驱动的《帝国与谜题》(Empires & Puzzles) 终极英雄资料与攻略平台。我们提供最新、最全面的<strong>英雄数据</strong>，包括星级、颜色、法速、职业、家族、起源及所有<strong>服装</strong>信息。",
        seoPara2: "本站的独特之处在于其强大的交互功能：使用我们强大的筛选系统，您不仅能按名称、来源等基本属性查找英雄，更能通过<strong>特殊技能文本</strong>、<strong>被动技能描述</strong>及精细的技能分类进行高级检索。独一无二的<strong>属性计算器</strong>，允许您实时查看英雄在不同极限突破（LB1/LB2）和天赋（+20/+25）等级下的确切战力、攻击、防御及生命值，为您的英雄成长规划提供数据支持。",
        seoPara3: "除了英雄数据库，我们还集成了多种实用工具来提升您的游戏体验：使用创新的【<strong>聊天模拟器</strong>】，您可以轻松制作带自定义颜色和游戏表情的聊天内容并一键复制；查阅我们详尽的【<strong>材料出处指南</strong>】和【<strong>通缉任务</strong>】速查表，高效定位资源，优化您的游戏攻略。您可以收藏您喜爱的英雄组合，并通过链接将您的<strong>收藏列表</strong>分享给盟友。平台完整支持简/繁中文和英文，并提供日/夜间模式切换功能。",
        pageTitle: "帝国与谜题英雄资料库 | Heroplan",
        headerTitle: "帝国与谜题英雄资料库", poweredBy: "由", driven: "驱动",
        sponsoredBy: "赞助", translatedBy: "译者制作", 
        donationListTitle: "感谢所有捐赠者的支持！",
        filterHeroes: "筛选英雄", standardFilters: "标准筛选", nameLabel: "名称:", searchLangTitle: '选择搜索语言',
        currentLangText: '🌐 当前', noMatchingResults: '无匹配结果',
        avatarLabel: "头像", namePlaceholder: "输入英雄名称", costumeTypeLabel: "服装类型:",
        starLabel: "星级:", colorLabel: "颜色:", speedLabel: "法速:", classLabel: "职业:", familyLabel: "家族:",
        sourceLabel: "起源:", aetherPowerLabel: "以太力量:", showEventNameLabel: "显示活动名称", filterHeroes: "筛选英雄",
        filterScopeLabel: "筛选范围:", filterScope_all: "全部",
        filterScope_hero: "英雄",
        filterScope_skin: "服装",
        filterScope_favorites: "收藏", clearSelection: "清空选择", advancedFilters: "高级筛选",
        skillTypeSourceLabel: "技能类别来源:", sourceBoth: "全部", sourceHeroplan: "Heroplan.io", sourceNynaeve: "By Nynaeve", sourceBbcamp: "bbcamp.info",
        skillTypeLabel: "特殊技能类别:", skillTypePlaceholder: "例如：增益,异常,治疗", skillTextLabel: "特殊技能文本:",
        passiveSkillLabel: "被动技能文本:", enableSkillQuickSearchLabel: "一键搜索技能词条:", cnSkill_baseLabel: "基础技能:",
        cnSkill_specialLabel: "特殊效果:",
        cnSkill_buffLabel: "增益效果:",
        cnSkill_debuffLabel: "负面效果:",
        enableSkillQuickSearchToggle: "启用", filterBy: "筛选:", all: "全部", hero: "英雄", skin: "服装", favorites: "收藏",
        heroAcademyEventLabel: "英雄学院10列表:", oneClickMaxEventLabel: "一键满级活动:", purchaseCostumeEventLabel: "购买服装活动:", 
        "soulExchangeEventLabel": "灵魂交换活动:",
        "showListBtnLabel": "展示列表",
        "soulExchangeModalTitle": "灵魂交换英雄列表",
        filterButtonLabel: "筛选",
        minPower: "战力", minAttack: "攻击", minDefense: "防御", minHealth: "生命", resetFilters: "重置筛选",
        hideDonate: "隐藏捐赠",
        showDonate: "显示捐赠",
        exportSettings: "导出设置",
        importSettings: "导入设置",
        importModalTitle: "导入设置",
        setting_heroFavorites: "收藏的英雄",
        setting_savedTeams: "已存的队伍",
        setting_favoriteColors: "聊天收藏颜色",
        setting_otherSettings: "界面及通用设置",
        exportModalTitle: "导出设置",
        exportItems: "选择要导出的项目：",
        importItems: "选择要导入的项目：",
        selectAll: "全选",
        exportSelected: "生成导出代码",
        analyzeCode: "解析代码",
        importSelected: "导入选中项",
        exportResultTitle: "您的导出代码（请复制并妥善保存）：",
        noDataToExport: "没有可供导出的数据。",
        noDataInCode: "代码中未发现可导入的数据或代码已损坏。",
        importInstructions: "请在下方粘贴您之前导出的设置代码:",
        importModeOverwrite: "覆盖模式：删除所有现有设置，并用导入的设置替换。",
        importModeAppend: "追加模式：保留现有设置，并将导入的设置合并进来（例如，收藏和已存队伍会合并去重）。",
        importConfirmBtn: "确认导入",
        importCancelBtn: "取消",
        importSettingsSuccess: (mode, counts) => { // 【新增】用于设置导入的成功提示
            if (mode === 'overwrite') {
                return '设置已成功覆盖导入！页面即将刷新以应用更改。';
            }
            // 追加模式
            const messages = [];
            if (counts.favorites > 0) messages.push(`新增 ${counts.favorites} 个收藏英雄`);
            if (counts.teams > 0) messages.push(`新增 ${counts.teams} 个队伍`);
            if (counts.colors > 0) messages.push(`新增 ${counts.colors} 个收藏颜色`);

            if (messages.length === 0) {
                return '导入完成，没有新增项目。页面即将刷新。';
            }
            return `设置已成功追加导入！\n${messages.join('，')}。\n页面即将刷新以应用更改。`;
        },
        importError: "导入失败！代码无效或已损坏。请检查代码是否完整。",
        saveToFile: "保存到文件",
        importFromFile: "从文件导入",
        shareFavorites: "分享收藏", openFavorites: "打开收藏", shareFavoritesCopied: "列表已复制!",
        footerGameName: "《帝国与谜题》", footerPlatform: "英雄数据查询平台",
        footerCredit: "© 2025 heroplan.github.io | 非官方资料站",
        resultsCountTextFiltered: (count) => `已筛选 ${count} 位英雄`,
        resultsCountTextUnfiltered: (count) => `${count} 位英雄 (包含服装)`,
        resultsCountTextHeroOnly: (count) => `${count} 位英雄 (不含服装)`,
        resultsCountTextCostumeOnly: (count) => `${count} 件服装`,
        favoritesListCount: (count) => `收藏列表共 ${count} 位英雄`,
        favoritesListEmpty: "收藏列表为空，请先收藏或重置筛选",
        resultsReset: "重置",
        noResults: "没有找到匹配的英雄", modalHeroDetails: "ℹ️ 英雄详情",
        closeBtnTitle: "关闭", modalOrigin: "起源", modalCoreStats: "📊 核心属性",
        limitBreakSetting: "突破设置:",
        noLimitBreak: "无突破",
        lb1: "🔼LB1",
        lb2: "⏫LB2",
        talentSetting: "天赋设置:",
        noTalent: "无天赋",
        talent20: "20 天赋",
        talent25: "25 天赋",
        prioritySetting: "天赋优先级:",
        attackPriority: "攻击 > 防御 > 生命",
        defensePriority: "防御 > 生命 > 攻击",
        attackPriority2: "攻击 > 生命 > 防御",
        healthPriority: "生命 > 防御 > 攻击",
        defensePriority2: "防御 > 攻击 > 生命",
        healthPriority2: "生命 > 攻击 > 防御",
        manaPriorityLabel: "法速节点:",
        manaPriorityToggle: "优先选择",
        showLbTalentDetailsLabel: "详情页突破天赋设置:",
        showLbTalentDetailsToggle: "显示",
        modalTalentSettingsTitle: "突破与天赋设置",
        customTalentTitle: "自定义天赋",
        talentTreeTitle: "职业天赋树", modalSettings: "设置", defaultStatSettingsTitle: "突破天赋设置", toggleCollapse: "点击折叠/展开", modalSkillDetails: "📖 技能详情",
        modalSkillName: "📄 名称:", modalSpeed: "⌛ 法速:", modalSkillType: "🏷️ 技能标签:",
        modalSpecialSkill: "✨ 技能效果:", modalPassiveSkill: "🧿 被动技能:",
        modalFamilyBonus: (family) => `👪 家族奖励 (${family}):`, modalSkin: "服装:", none: "无", detailsCloseBtn: "关闭",
        shareButtonTitle: "分享", favoriteButtonTitle: "收藏", favColumnHeader: "☆",
        favHeaderTitle: "一键收藏/取消全部",
        confirmFavoriteAll: "您确定要收藏当前列表中的所有英雄吗？",
        confirmUnfavoriteAll: "您确定要取消收藏当前列表中的所有英雄吗？",
        filterHelpTitle: "高级筛选语法说明",
        filterHelpIntro: "在“特殊技能/被动技能”输入框中，您可使用以下操作符构建复杂查询：",
        filterHelpOr: "<li><strong>| (或):</strong> 查找包含多个关键词中任意一个的英雄。例如: <code>治疗|复活</code> 会找到技能中包含“治疗”或“复活”的英雄。</li>",
        filterHelpAnd: "<li><strong>空格 (与):</strong> 查找必须同时包含多个关键词的英雄。例如: <code>攻击 提高</code> 会找到技能中同时包含“攻击”和“提升”的英雄。</li>",
        filterHelpNot: "<li><strong>! (非):</strong> 排除包含特定关键词的英雄。例如: <code>!治疗</code> 会找到所有技能中不含“治疗”的英雄。</li>",
        filterHelpGroup: "<li><strong>() (分组/单句匹配):</strong> 使用括号进行复杂组合时，<strong style='color: var(--md-sys-color-error);'>强制在单句技能描述中进行匹配</strong>。例如: <code>(抵抗 治疗)</code> 会查找在单句中同时包含“抵抗”和“治疗”的英雄。</li>",
        filterHelpExact: "<li><strong>[] (完全匹配):</strong> 使用方括号可<strong style='color: var(--md-sys-color-error);'>强制单条技能类别完全匹配</strong>。例如: <code>[净化]</code> 会精确寻找技能类别为“净化”的英雄，而不会匹配到“高级净化”或“净化格挡者”。</li>",
        filterHelpExample: "<li><strong>综合示例:</strong> <code>((免疫|反弹) 增益)</code> 会查找能提供免疫或反弹增益的英雄（且所有条件需在同一句描述中满足）。</li>",
        skillTypeHelpTitle: "技能类别来源说明",
        skillTypeHelpContent: `<p>您可以选择不同的技能分类标签来源进行筛选：</p><ul><li><strong>Heroplan.io:</strong> 数据来自 <a href="https://heroplan.io/" target="_blank" rel="noopener noreferrer">Heroplan.io</a> 网站。</li><li><strong>By Nynaeve:</strong> 数据来自 <a href="http://www.theravenscave.com/" target="_blank" rel="noopener noreferrer">www.theravenscave.com</a>，经过AI补全和人工审核。(标签定义包括了技能本身和必定触发的被动、家族奖励而制作)</li><li><strong>bbcamp.info:</strong> 标签定义参考<a href="https://bbcamp.info" target="_blank" rel="noopener noreferrer">bbcamp.info</a>，经过AI修正和人工审核。(只专注于技能本身效果,而且忽略了元素链的效果,可在标准筛选处筛选)</li><li><strong>全部:</strong> 同时搜索以上所有来源的标签。</li></ul><p>各类别的详细定义，请参考源网站。</p>`,
        noFavoritesToShare: "没有可分享的收藏。",
        copyLinkFailed: "复制链接失败，请尝试手动复制。",
        wantedMissionTableTitle: "通缉任务表",
        farmingGuideTableTitle: "材料出处指南",
        questHeaderDaily: "日常",
        questHeaderRed: "红",
        questHeaderGreen: "绿",
        questHeaderBlue: "蓝",
        questHeaderPurple: "紫",
        questHeaderYellow: "黄",
        toggleThemeTitle: "切换日间/夜间模式",
        toggleLanguageTitle: "切换语言",
        showLotterySimulatorTitle: "抽奖模拟器",
        showTeamSimulatorTitle: "队伍模拟器",
        showChatSimulatorTitle: "聊天模拟器",
        showFarmingGuideTitle: "材料出处指南",
        showWantedMissionTitle: "显示通缉任务表",
        openFiltersTitle: "打开筛选",
        calendarTitle: "查看活动日历",
        filterSyntaxTitle: "筛选语法说明",
        skillTypeSourceHelpTitle: "技能类别来源说明",
        lotterySimulatorTitle: "抽奖模拟器",
        returnToList: "返回",
        teamDisplayTitle: "阵容配置",
        noTeamTags: "队伍中暂无技能标签",
        saveTeamBtn: "保存队伍",
        shareTeamListBtn: "分享列表",
        savedTeamsTitle: "已存队伍",
        promptTeamName: "为您的队伍命名:",
        teamNameRequired: "队伍名称不能为空。",
        noHeroesInTeam: "队伍中没有英雄可供保存。",
        removeTeamBtnTitle: "移除此队伍",
        noSavedTeams: "没有已保存的队伍。",
        confirmRemoveTeam: (name) => `您确定要移除队伍 "${name}" 吗？`,
        shareTeamListCopied: "链接已复制!",
        noTeamsToShare: "没有可分享的队伍。", 
        clearTeamBtn: "清空阵容",
        confirmClearTeam: "您确定要清空当前阵容吗？所有未保存的更改都将丢失。",
        importSuccess: (teamName) => `队伍 "${teamName}" 已成功导入！`,
        importConfirmOverwrite: (teamName) => `队伍 "${teamName}" 已存在。您想覆盖它吗？`,
        importEnterNewName: (teamName) => `队伍 "${teamName}" 已存在。请输入一个新的名称以导入：`,
        importedBtn: "已导入",
        importTeamBtn: "导入",
        teamImportedBtn: "已导入",
        sharedTeamsTitle: "分享的队伍", 
        myTeamsTab: "我的队伍",
        sharedTeamsTab: "分享的队伍",
        summaryTagsTitle: "技能标签汇总",
        // --- 聊天模拟器新增文本 ---
        showChatSimulatorTitle: "聊天模拟器",
        chatSimulatorTitle: "聊天模拟器",
        chatPanelTitleColors: "选择颜色",
        chatPanelTitleEmojis: "选择表情",
        chatFavoriteColorBtn: "⭐",
        chatFavoriteColorsTitle: "已收藏的颜色",
        chatPanelTitleIO: "输入与预览",
        chatInsertColorBtn: "插入",
        chatCopyBtn: "复制内容",
        chatCopied: "已复制!",
        talentTerms: {
            '攻击': '攻击',
            '防御': '防御',
            '生命': '生命',
            '法力': '法力',
            '治疗': '治疗',
            '暴击': '暴击',
            '游侠天赋': '游侠天赋', '战士天赋': '战士天赋', '圣骑天赋': '圣骑天赋',
            '野蛮人天赋': '野蛮人天赋', '牧师天赋': '牧师天赋', '德鲁伊天赋': '德鲁伊天赋',
            '僧侣天赋': '僧侣天赋', '盗贼天赋': '盗贼天赋', '术士天赋': '术士天赋', '巫师天赋': '巫师天赋',
            '游侠终极天赋': '游侠终极天赋', '战士终极天赋': '战士终极天赋', '圣骑士终极天赋': '圣骑士终极天赋',
            '野蛮人终极天赋': '野蛮人终极天赋', '牧师终极天赋': '牧师终极天赋', '德鲁伊终极天赋': '德鲁伊终极天赋',
            '僧侣终极天赋': '僧侣终极天赋', '盗贼终极天赋': '盗贼终极天赋', '术士终极天赋': '术士终极天赋', '巫师终极天赋': '巫师终极天赋',
        },
        bonusAndCostTitle: "加成与消耗",
        attackBonusLabel: "攻击:",
        defenseBonusLabel: "防御:",
        healthBonusLabel: "生命:",
        manaBonusLabel: "法力:",
        healingBonusLabel: "治疗:",
        critBonusLabel: "暴击:",
        noBonusLabel: "未获得任何属性加成",
        emblemCostLabel: "纹章:",
        foodCostLabel: "食物:",
        ironCostLabel: "铁矿:",
        masterEmblemCostLabel: "大师纹章:",
        lbTalentHelpTitle: "突破与天赋设置说明",
        lbTalentHelpLine1: "突破后属性数据来自 <a href='https://bbcamp.info' target='_blank' rel='noopener noreferrer'>https://bbcamp.info</a>",
        lbTalentHelpLine2: "法力优先则以法力为最优先级，必定升级法力的天赋。",
        viewLatest: '查看最新',
        modalAttributeTalentBtn: '属性天赋',
        modalSkillTagsHeader: '📖 技能详情', 
        modalSkillDetailsBtn: '技能标签',
        modalSkillEffectBtn: '技能效果',
        modalPassiveBtn: '被动技能',
        modalFamilyBonusBtn: '家族奖励',
        // --- 抽奖模拟器新增文本 ---
        lotterySimulatorTitle: "抽奖模拟器",
        summonOnce: "召唤",
        summonTen: "召唤x10",
        summonThirty: "召唤x30",
        confirmClearHistory: "确定要清空所有召唤历史记录吗？",
        "toggleShowAllHistoryLabel": "显示全部记录",
        "confirmClearCurrentHistory": "确定要清空当前活动的召唤记录吗？",
        "summonHistoryTitleCurrent": (poolName, count) => `${poolName} 召唤记录 (共 ${count} 次)`,
        "summonHistoryTitleAll": "全部召唤历史记录",
        "calculatedProbabilitiesTitle": "本活动召唤概率统计",
        noSummonHistory: "没有召唤历史",
        clearHistoryBtn: "清空",
        summonResultsTitle: "召唤结果",
        skipAnimation: "跳过动画",
        lotteryTabActivity: "活动列表",
        lotteryTabSummon: "召唤",
        summonHistoryTitle: "召唤历史记录",
        lotteryTabHistory: "历史记录",
        probabilityInfoTitle: "概率详情",
        StageGuideTitle: "关卡指南",
        probabilityInfoIntro: "当前卡池的召唤概率:",
        lottery_bucket_translations: { 
            // 抽奖详情桶翻译
            "heroes_ex_s1_3": "非经典英雄(3星)",
            "heroes_ex_s1_4": "非经典英雄(4星)",
            "heroes_ex_s1_5": "非经典英雄(非精选)(5星)",
            "heroes_s1_3": "经典英雄(3星)",
            "heroes_s1_4": "经典英雄(4星)",
            "heroes_s1_5": "经典英雄(5星)",
            "heroes_event_3": "活动英雄(3星)",
            "heroes_event_4": "活动英雄(4星)",
            "heroes_event_5": "活动英雄(非精选)(5星)",
            "heroes_listed_3": "特选列表英雄(3星)",
            "heroes_listed_4": "特选列表英雄(4星)",
            "heroes_listed_5": "特选列表英雄(非精选)(5星)",
            "heroes_extraAssociatedFamilies_3": "附加家族英雄(3星)",
            "heroes_extraAssociatedFamilies_4": "附加家族英雄(4星)",
            "heroes_extraAssociatedFamilies_5": "附加家族英雄(5星)",
            "featuredHero": "精选英雄(5星)",
            "trainer_3": "训练师(3星)",
            "trainer_4": "训练师(4星)",
        },
        "lottery_bonus_translations": {
            "bonusProbabilityTitle": "额外概率",
            "hotm": "月度英雄概率",
            "MysteryHero": "神秘英雄概率",
            "LegendsSummonMysteryHero": "神话召唤神秘英雄概率",
            "additionalDrawWeights": "单次召唤总数概率",
            "bonusLegendaryHeroChancePerMil": "奖励传奇英雄概率",
            "bonusLegendaryHeroChancePerMil": "奖励概率", 
            "bonusLegendaryHeroType": "奖励英雄类型",
            "bonusLegendaryProbabilityTitle": "额外传奇英雄",
            "bonusLegendaryHeroPullAmount": "奖励抽取次数"
        },
        "lottery_bonus_values": {
            "eventHeroesOnly": "活动英雄",
            "NonClassicHero": "非经典英雄" 
        },
        "selectElementTitle": "请选择元素",
        "superElementalExclusionNotice": (days) => `* 不包含${days}天内发布的非活动家族英雄`,
        "noMysteryBonusNotice": "此召唤不包含当前的秘密英雄的额外抽取机会。",
        "includesTrainerNotice": "* 此奖池包含训练师。",
        "summonSummaryOkBtn": "确定",
        "playMode_full": "播放完整动画",
        "playMode_skip": "跳过动画，显示结果",
        "playMode_silent": "直接记录，不显示结果",
        "muteSound": "静音",
        "unmuteSound": "取消静音",
        "featuredHeroRequired": '请在下方表格使用⬆️,至少设置一位精选英雄后再进行召唤。',
        "mustSelect5StarHero": "请选择一位5星英雄。",
        "featuredSlotsFull": '所有精选英雄卡槽已满，可双击精选英雄头像移除。',
        "totalHeroesCountText": (count) => `(共 ${count} 位)`,
        "latestHeroAgeNotice": (days) => `* 仅包含 ${days} 天内发布的英雄和服装`,
        "w3kLimitedPoolTitle": "查看三国限定奖池",
        "showRedeemCodesTitle": "查看可用兑换码",
        "redeemCodesModalTitle": "可用兑换码",
        "redeemBtn": '兑换', 
        highlightSkillTermsLabel: "高亮技能词条:",
        highlightSkillTermsToggle: "启用",
        showSkillTypesInDetailsLabel: "详情页显示技能类别:",
        showSkillTypesInTeamLabel: "队伍模拟器显示技能类别:",
        showSkillTypesToggle: "启用",
        showCircleRayLabel: "英雄立绘中显示元素光效:",
        showCircleRayToggle: "启用",


    },
    tc: {
        metaDescription: "Heroplan是為《帝國與謎題》(Empires & Puzzles)玩家打造的終極英雄資料庫。快速查詢和比較所有英雄的詳細數據、特殊技能、家族加成和攻略資訊。",
        seoHeading: "《帝國與謎題》一站式英雄資料庫與玩家工具箱",
        seoPara1: "歡迎使用由 <strong>Heroplan.io</strong> 驅動的《帝國與謎題》(Empires & Puzzles) 終極英雄資料與攻略平台。我們提供最新、最全面的<strong>英雄數據</strong>，包括星級、顏色、法速、職業、家族、起源及所有<strong>服裝</strong>資訊。",
        seoPara2: "本站的獨特之處在於其強大的互動功能：使用我們強大的篩選系統，您不僅能按名稱、來源等基本屬性查找英雄，更能透過<strong>特殊技能文本</strong>、<strong>被動技能描述</strong>及精細的技能分類進行進階檢索。獨一無二的<strong>屬性計算器</strong>，允許您即時查看英雄在不同極限突破（LB1/LB2）和天賦（+20/+25）等級下的確切戰力、攻擊、防禦及生命值，為您的英雄成長規劃提供數據支援。",
        seoPara3: "除了英雄資料庫，我們還整合了多種實用工具來提升您的遊戲體驗：使用創新的【<strong>聊天模擬器</strong>】，您可以輕鬆製作帶自訂顏色和遊戲表情的聊天內容並一鍵複製；查閱我們詳盡的【<strong>材料出處指南</strong>】和【<strong>通緝任務</strong>】速查表，高效定位資源，最佳化您的遊戲攻略。您可以收藏您喜愛的英雄組合，並透過連結將您的<strong>收藏列表</strong>分享給盟友。平台完整支援簡/繁中文和英文，並提供日/夜間模式切換功能。",
        pageTitle: "帝國與謎題英雄資料庫 | Heroplan",
        headerTitle: "帝國與謎題英雄資料庫", poweredBy: "由", driven: "驅動",
        sponsoredBy: "贊助", translatedBy: "譯者製作", 
        donationListTitle: "感謝所有捐贈者的支持！",
        filterHeroes: "篩選英雄", standardFilters: "標準篩選", nameLabel: "名稱:", searchLangTitle: '選擇搜索語言',
        currentLangText: '🌐 當前', 'noMatchingResults': '無匹配結果', 
        avatarLabel: "頭像", namePlaceholder: "輸入英雄名稱", costumeTypeLabel: "服裝類型:",
        starLabel: "星級:", colorLabel: "顏色:", speedLabel: "法速:", classLabel: "職業:", familyLabel: "家族:",
        sourceLabel: "起源:", aetherPowerLabel: "以太力量:", showEventNameLabel: "顯示活動名稱", filterHeroes: "筛选英雄", 
        filterScopeLabel: "篩選範圍:", filterScope_all: "全部",
        filterScope_hero: "英雄",
        filterScope_skin: "服裝",
        filterScope_favorites: "收藏", clearSelection: "清空選擇", advancedFilters: "高級篩選",
        skillTypeSourceLabel: "技能類別來源:", sourceBoth: "全部", sourceHeroplan: "Heroplan.io", sourceNynaeve: "By Nynaeve", sourceBbcamp: "bbcamp.info",
        skillTypeLabel: "特殊技能類別:", skillTypePlaceholder: "例如：增益,異常,治療", skillTextLabel: "特殊技能文本:",
        passiveSkillLabel: "被動技能文本:", enableSkillQuickSearchLabel: "一鍵搜尋技能詞條:", cnSkill_baseLabel: "基礎技能:",
        cnSkill_specialLabel: "特殊效果:",
        cnSkill_buffLabel: "增益效果:",
        cnSkill_debuffLabel: "負面效果:",
        enableSkillQuickSearchToggle: "啟用", filterBy: "篩選:", all: "全部", hero: "英雄", skin: "服裝", favorites: "收藏",
        heroAcademyEventLabel: "英雄學院10列表:", oneClickMaxEventLabel: "一鍵滿級活動:", purchaseCostumeEventLabel: "購買服裝活動:",
        "soulExchangeEventLabel": "靈魂交換活動:",
        "showListBtnLabel": "展示列表",
        "soulExchangeModalTitle": "靈魂交換英雄列表",
        filterButtonLabel: "篩選",
        minPower: "戰力", minAttack: "攻擊", minDefense: "防禦", minHealth: "生命", resetFilters: "重置篩選",
        hideDonate: "隱藏捐贈",
        showDonate: "顯示捐贈",
        exportSettings: "導出設定",
        importSettings: "導入設定",
        setting_heroFavorites: "收藏的英雄",
        setting_savedTeams: "已存的隊伍",
        setting_favoriteColors: "聊天收藏顏色",
        setting_otherSettings: "界面及通用設定",
        exportModalTitle: "匯出設定",
        importModalTitle: "導入設定",
        exportItems: "選擇要匯出的項目：",
        importItems: "選擇要導入的項目：",
        selectAll: "全選",
        exportSelected: "生成匯出代碼",
        analyzeCode: "解析代碼",
        importSelected: "導入選中項",
        exportResultTitle: "您的匯出代碼（請複製並妥善保存）：",
        noDataToExport: "沒有可供匯出的數據。",
        noDataInCode: "代碼中未發現可導入的數據或代碼已損壞。",
        importInstructions: "請在下方貼上您先前導出的設定代碼:",
        importModeOverwrite: "覆蓋模式：刪除所有現有設定，並用導入的設定替換。",
        importModeAppend: "追加模式：保留現有設定，並將導入的設定合併進來（例如，收藏和已存隊伍會合併去重）。",
        importConfirmBtn: "確認導入",
        importCancelBtn: "取消",
        importSettingsSuccess: (mode, counts) => { // 【新增】
            if (mode === 'overwrite') {
                return '設定已成功覆蓋導入！頁面即將刷新以應用更改。';
            }
            // 追加模式
            const messages = [];
            if (counts.favorites > 0) messages.push(`新增 ${counts.favorites} 個收藏英雄`);
            if (counts.teams > 0) messages.push(`新增 ${counts.teams} 個隊伍`);
            if (counts.colors > 0) messages.push(`新增 ${counts.colors} 個收藏顏色`);

            if (messages.length === 0) {
                return '導入完成，沒有新增項目。頁面即將刷新。';
            }
            return `設定已成功追加導入！\n${messages.join('，')}。\n頁面即將刷新以應用更改。`;
        },
        importError: "導入失敗！代碼無效或已損壞。請檢查代碼是否完整。",
        saveToFile: "儲存至檔案",
        importFromFile: "從檔案匯入",
        shareFavorites: "分享收藏", openFavorites: "打開收藏", shareFavoritesCopied: "列表已複製!",
        footerGameName: "《帝國與謎題》", footerPlatform: "英雄數據查詢平台",
        footerCredit: "© 2025 heroplan.github.io | 非官方資料站",
        resultsCountTextFiltered: (count) => `已篩選 ${count} 位英雄`,
        resultsCountTextUnfiltered: (count) => `${count} 位英雄 (包含服裝)`,
        resultsCountTextHeroOnly: (count) => `${count} 位英雄 (不含服裝)`,
        resultsCountTextCostumeOnly: (count) => `${count} 件服裝`,
        favoritesListCount: (count) => `收藏清單共 ${count} 位英雄`,
        favoritesListEmpty: "收藏清單為空，請先收藏或重設篩選",
        resultsReset: "重設",
        noResults: "沒有找到匹配的英雄", modalHeroDetails: "ℹ️ 英雄詳情",
        closeBtnTitle: "關閉", modalOrigin: "起源", modalCoreStats: "📊 核心屬性",
        limitBreakSetting: "突破設置:",
        noLimitBreak: "無突破",
        lb1: "🔼LB1",
        lb2: "⏫LB2",
        talentSetting: "天賦設置:",
        noTalent: "無天賦",
        talent20: "20 天賦",
        talent25: "25 天賦",
        prioritySetting: "天賦優先級:",
        attackPriority: "攻擊 > 防禦 > 生命",
        defensePriority: "防禦 > 生命 > 攻擊",
        attackPriority2: "攻擊 > 生命 > 防禦",
        healthPriority: "生命 > 防禦 > 攻擊",
        defensePriority2: "防禦 > 攻擊 > 生命",
        healthPriority2: "生命 > 攻擊 > 防禦",
        manaPriorityLabel: "法速節點:",
        manaPriorityToggle: "優先選擇",
        showLbTalentDetailsLabel: "詳情頁突破天賦設置:",
        showLbTalentDetailsToggle: "顯示",
        modalTalentSettingsTitle: "突破與天賦設置",
        customTalentTitle: "自訂天賦",
        talentTreeTitle: "職業天賦樹", modalSettings: "設置", defaultStatSettingsTitle: "突破天賦設置", toggleCollapse: "點擊折疊/展開", modalSkillDetails: "📖 技能詳情",
        modalSkillName: "📄 名稱:", modalSpeed: "⌛ 法速:", modalSkillType: "🏷️ 技能標籤:",
        modalSpecialSkill: "✨ 技能效果:", modalPassiveSkill: "🧿 被動技能:",
        modalFamilyBonus: (family) => `👪 家族獎勵 (${family}):`, modalSkin: "服裝:", none: "無", detailsCloseBtn: "關閉",
        shareButtonTitle: "分享", favoriteButtonTitle: "收藏", favColumnHeader: "☆",
        favHeaderTitle: "一鍵收藏/取消全部",
        confirmFavoriteAll: "您確定要收藏當前列表中的所有英雄嗎？",
        confirmUnfavoriteAll: "您確定要取消收藏當前列表中的所有英雄嗎？",
        filterHelpTitle: "高級篩選語法說明",
        filterHelpIntro: "在“特殊技能/被動技能”輸入框中，您可使用以下運算子構建複雜查詢：",
        filterHelpOr: "<li><strong>| (或):</strong> 尋找包含多個關鍵詞中任意一個的英雄。例如: <code>治療|復活</code> 會找到技能中包含“治療”或“復活”的英雄。</li>",
        filterHelpAnd: "<li><strong>空格 (與):</strong> 尋找必須同時包含多個關鍵詞的英雄。例如: <code>攻擊 提升</code> 會找到技能中同時包含“攻擊”和“提升”的英雄。</li>",
        filterHelpNot: "<li><strong>! (非):</strong> 排除包含特定關鍵詞的英雄。例如: <code>!治療</code> 會找到所有技能中不含“治療”的英雄。</li>",
        filterHelpGroup: "<li><strong>() (分組/單句匹配):</strong> 使用括號可进行复杂组合，并<strong style='color: var(--md-sys-color-error);'>强制在单句技能描述中进行匹配</strong>。例如: <code>(抵禦 治療)</code> 會精確尋找<strong style='color: var(--md-sys-color-error);'>某一句</strong>技能描述中，同時包含“抵禦”和“治療”的英雄。</li>",
        filterHelpExact: "<li><strong>[] (完全匹配):</strong> 使用方括號可<strong style='color: var(--md-sys-color-error);'>強制單條技能類別完全匹配</strong>。例如: <code>[凈化]</code> 會精確尋找技能類別為“凈化”的英雄，而不會匹配到“高級凈化”或“凈化格擋者”。</li>",
        filterHelpExample: "<li><strong>綜合示例:</strong> <code>((免疫|反射) 增益)</code> 會尋找能提供免疫或反射增益的英雄（且所有條件需在同一句描述中滿足）。</li>",
        skillTypeHelpTitle: "技能類別來源說明",
        skillTypeHelpContent: `<p>您可以選擇不同的技能分類標籤來源進行篩選：</p><ul><li><strong>Heroplan.io:</strong> 資料來自 <a href="https://heroplan.io/" target="_blank" rel="noopener noreferrer">Heroplan.io</a> 網站。</li><li><strong>By Nynaeve:</strong> 資料來自 <a href="http://www.theravenscave.com/" target="_blank" rel="noopener noreferrer">www.theravenscave.com</a>，經過AI補全和人工審核。(標籤定義包括了技能本身和必定觸發的被動、家族獎勵而製作)</li><li><strong>bbcamp.info:</strong> 標籤定義參考<a href="https://bbcamp.info" target="_blank" rel="noopener noreferrer">bbcamp.info</a>，經過AI修正和人工審核。(只專注於技能本身效果,而且忽略了元素鏈的效果,可在標準篩選處篩選)</li><li><strong>全部:</strong> 同時搜索以上所有來源的標籤。</li></ul><p>各類別的詳細定義，請參考源網站。</p>`,
        noFavoritesToShare: "沒有可分享的收藏。",
        copyLinkFailed: "複製鏈接失敗，請嘗試手動複製。",
        wantedMissionTableTitle: "通緝任務表",
        farmingGuideTableTitle: "材料出處指南",
        questHeaderDaily: "日常",
        questHeaderRed: "紅",
        questHeaderGreen: "綠",
        questHeaderBlue: "藍",
        questHeaderPurple: "紫",
        questHeaderYellow: "黃",
        toggleThemeTitle: "切換日間/夜間模式",
        toggleLanguageTitle: "切換語言",
        showLotterySimulatorTitle: "抽獎模擬器",
        showTeamSimulatorTitle: "隊伍模擬器",
        showChatSimulatorTitle: "聊天模擬器",
        showFarmingGuideTitle: "材料出處指南",
        showWantedMissionTitle: "顯示通緝任務表",
        openFiltersTitle: "打開篩選",
        calendarTitle: "查看活動日曆",
        filterSyntaxTitle: "篩選語法說明",
        skillTypeSourceHelpTitle: "技能類別來源說明",
        lotterySimulatorTitle: "抽獎模擬器",
        returnToList: "返回",
        teamDisplayTitle: "陣容配置",
        noTeamTags: "隊伍中暫無技能標籤",
        saveTeamBtn: "儲存隊伍",
        shareTeamListBtn: "分享列表",
        savedTeamsTitle: "已存隊伍",
        promptTeamName: "為您的隊伍命名:",
        teamNameRequired: "隊伍名稱不能為空。",
        noHeroesInTeam: "隊伍中沒有英雄可供儲存。",
        removeTeamBtnTitle: "移除此隊伍",
        noSavedTeams: "沒有已儲存的隊伍。",
        confirmRemoveTeam: (name) => `您確定要移除隊伍 "${name}" 嗎？`,
        shareTeamListCopied: "連結已複製!",
        noTeamsToShare: "沒有可分享的隊伍。",
        clearTeamBtn: "清空陣容",
        confirmClearTeam: "您確定要清空當前陣容嗎？所有未儲存的變更都將遺失。",
        importSuccess: (teamName) => `隊伍 "${teamName}" 已成功匯入！`,
        importConfirmOverwrite: (teamName) => `隊伍 "${teamName}" 已存在。您想覆蓋它嗎？`,
        importTeamBtn: "匯入",
        importEnterNewName: (teamName) => `隊伍 "${teamName}" 已存在。請輸入一個新的名稱以匯入：`,
        importedBtn: "已匯入",
        teamImportedBtn: "已匯入",
        sharedTeamsTitle: "分享的隊伍",
        myTeamsTab: "我的隊伍",
        sharedTeamsTab: "分享的隊伍",
        summaryTagsTitle: "技能標籤匯總",
        // --- 聊天模擬器新增文本 ---
        showChatSimulatorTitle: "聊天模擬器",
        chatSimulatorTitle: "聊天模擬器",
        chatPanelTitleColors: "選擇顏色",
        chatFavoriteColorBtn: "⭐",
        chatFavoriteColorsTitle: "已收藏的顏色",
        chatPanelTitleEmojis: "選擇表情",
        chatPanelTitleIO: "輸入與預覽",
        chatInsertColorBtn: "插入",
        chatCopyBtn: "複製內容",
        chatCopied: "已複製!",
        talentTerms: {
            '攻击': '攻擊',
            '防御': '防禦',
            '生命': '生命',
            '法力': '法力',
            '治疗': '治療',
            '暴击': '暴擊',
            '游侠天赋': '遊俠天賦', '战士天赋': '戰士天賦', '圣骑天赋': '聖騎天賦',
            '野蛮人天赋': '野蠻人天賦', '牧师天赋': '牧師天賦', '德鲁伊天赋': '德魯伊天賦',
            '僧侣天赋': '僧侶天賦', '盗贼天赋': '盜賊天賦', '术士天赋': '術士天賦', '巫师天赋': '巫師天賦',
            '游侠终极天赋': '遊俠終極天賦', '战士终极天赋': '戰士終極天賦', '圣骑士终极天赋': '騎士終極天賦',
            '野蛮人终极天赋': '野蠻人終極天賦', '牧师终极天赋': '牧師終極天賦', '德鲁伊终极天赋': '德魯伊終極天賦',
            '僧侣终极天赋': '僧侶終極天賦', '盗贼终极天赋': '盜賊終極天賦', '术士终极天赋': '術士終極天賦', '巫师终极天赋': '巫師終極天賦',
        },
        bonusAndCostTitle: "加成與消耗",
        attackBonusLabel: "攻擊:",
        defenseBonusLabel: "防禦:",
        healthBonusLabel: "生命:",
        manaBonusLabel: "法力:",
        healingBonusLabel: "治療:",
        critBonusLabel: "暴擊:",
        noBonusLabel: "未獲得任何屬性加成",
        emblemCostLabel: "紋章:",
        foodCostLabel: "食物:",
        ironCostLabel: "鐵礦:",
        masterEmblemCostLabel: "大師紋章:",
        lbTalentHelpTitle: "突破與天賦設置說明",
        lbTalentHelpLine1: "突破後屬性數據來自 <a href='https://bbcamp.info' target='_blank' rel='noopener noreferrer'>https://bbcamp.info</a>",
        lbTalentHelpLine2: "法力優先則以法力為最優先級,必定升級法力的天賦。",
        viewLatest: '查看最新',
        modalAttributeTalentBtn: '屬性天賦',
        modalSkillTagsHeader: '📖 技能詳情',
        modalSkillDetailsBtn: '技能標籤',
        modalSkillEffectBtn: '技能效果',
        modalPassiveBtn: '被動技能',
        modalFamilyBonusBtn: '家族獎勵',
        // --- 抽奖模拟器新增文本 ---
        lotterySimulatorTitle: "抽獎模擬器",
        summonOnce: "召喚",
        summonTen: "召喚x10",
        summonThirty: "召喚x30",
        confirmClearHistory: "確定要清空所有召喚歷史記錄嗎？",
        "toggleShowAllHistoryLabel": "顯示全部記錄",
        "confirmClearCurrentHistory": "確定要清空當前活動的召喚記錄嗎？",
        "summonHistoryTitleCurrent": (poolName, count) => `${poolName} 召喚記錄 (共 ${count} 次)`,
        "summonHistoryTitleAll": "全部召喚歷史記錄",
        "calculatedProbabilitiesTitle": "本活动召喚機率統計",
        noSummonHistory: "沒有召喚歷史",
        clearHistoryBtn: "清空",
        summonResultsTitle: "召喚結果",
        skipAnimation: "跳過動畫",
        lotteryTabActivity: "活動列表",
        lotteryTabSummon: "召喚",
        summonHistoryTitle: "召喚歷史",
        lotteryTabHistory: "歷史記錄",
        probabilityInfoTitle: "機率詳情",
        StageGuideTitle: "關卡指南",
        probabilityInfoIntro: "當前卡池的召喚機率:", 
        lottery_bucket_translations: {
            // 抽獎詳情桶翻譯
            "heroes_ex_s1_3": "非經典英雄(3星)",
            "heroes_ex_s1_4": "非經典英雄(4星)",
            "heroes_ex_s1_5": "非經典英雄(非精選)(5星)",
            "heroes_s1_3": "經典英雄(3星)",
            "heroes_s1_4": "經典英雄(4星)",
            "heroes_s1_5": "經典英雄(5星)",
            "heroes_event_3": "活動英雄(3星)",
            "heroes_event_4": "活動英雄(4星)",
            "heroes_event_5": "活動英雄(非精選)(5星)",
            "heroes_listed_3": "特選列表英雄(3星)",
            "heroes_listed_4": "特選列表英雄(4星)",
            "heroes_listed_5": "特選列表英雄(非精選)(5星)",
            "heroes_extraAssociatedFamilies_3": "附加家族英雄(3星)",
            "heroes_extraAssociatedFamilies_4": "附加家族英雄(4星)",
            "heroes_extraAssociatedFamilies_5": "附加家族英雄(5星)",
            "featuredHero": "精選英雄(5星)",
            "trainer_3": "訓練師(3星)",
            "trainer_4": "訓練師(4星)",
        },
        "lottery_bonus_translations": {
            "bonusProbabilityTitle": "額外機率",
            "hotm": "月度英雄機率",
            "MysteryHero": "神秘英雄機率",
            "LegendsSummonMysteryHero": "傳奇召喚神秘英雄機率",
            "additionalDrawWeights": "單次召喚總數機率",
            "bonusLegendaryHeroChancePerMil": "獎勵機率",
            "bonusLegendaryHeroType": "獎勵英雄類型",
            "bonusLegendaryProbabilityTitle": "額外傳奇英雄",
            "bonusLegendaryHeroPullAmount": "獎勵抽取次數"
        },
        "lottery_bonus_values": {
            "eventHeroesOnly": "活動英雄",
            "NonClassicHero": "非經典英雄"
        },
        "selectElementTitle": "請選擇元素",
        "superElementalExclusionNotice": (days) => `* 不包含${days}天內發佈的非活動家族英雄`,
        "noMysteryBonusNotice": "此召喚不包含当前秘密英雄的額外抽取機會。",
        "includesTrainerNotice": "* 此獎池包含訓練師。",
        "summonSummaryOkBtn": "確定",
        "playMode_full": "播放完整動畫", 
        "playMode_skip": "跳過動畫，顯示結果", 
        "playMode_silent": "直接記錄，不顯示結果", 
        "muteSound": "靜音",
        "unmuteSound": "取消靜音",
        "featuredHeroRequired": '請在下方表格使用⬆️,至少設置一位精選英雄後再進行召喚。',
        "mustSelect5StarHero": "請選擇一位5星英雄。",
        "featuredSlotsFull": '所有精選英雄卡槽已滿，可雙擊精選英雄頭像移除。',
        "totalHeroesCountText": (count) => `(共 ${count} 位)`,
        "latestHeroAgeNotice": (days) => `* 僅包含 ${days} 天內發佈的英雄和服裝`,
        "w3kLimitedPoolTitle": "查看三國限定獎池",
        "showRedeemCodesTitle": "查看可用兌換碼",
        "redeemCodesModalTitle": "可用兌換碼",
        "redeemBtn": '兌換',
        highlightSkillTermsLabel: "高亮技能詞條:",
        highlightSkillTermsToggle: "啟用",
        showSkillTypesInDetailsLabel: "詳情頁顯示技能類別:",
        showSkillTypesInTeamLabel: "隊伍模擬器顯示技能類別:",
        showSkillTypesToggle: "啟用",
        showCircleRayLabel: "英雄立繪中顯示元素光效:",
        showCircleRayToggle: "啟用",

    },
    en: {
        metaDescription: "The ultimate hero database for Empires & Puzzles players. Quickly search and compare detailed stats, special skills, family bonuses, and strategy guides for all heroes.",
        seoHeading: "Empires & Puzzles One-Stop Hero Database & Player Toolbox",
        seoPara1: "Welcome to the ultimate hero data and strategy platform for Empires & Puzzles, powered by <strong>Heroplan.io</strong>. We provide the latest and most comprehensive <strong>hero data</strong>, including star rating, color, speed, class, family, origin, and all <strong>costume</strong> information.",
        seoPara2: "What makes this site unique are its powerful interactive features: use our robust filtering system to find heroes not only by basic attributes like name and origin, but also through advanced searches of <strong>special skill text</strong>, <strong>passive descriptions</strong>, and detailed skill categories. The one-of-a-kind <strong>Stat Calculator</strong> allows you to see the exact power, attack, defense, and health of a hero at different Limit Break (LB1/LB2) and Talent (+20/+25) levels, providing data-driven support for your hero development plans.",
        seoPara3: "In addition to the hero database, we've integrated several useful tools to enhance your gameplay: use the innovative [<strong>Chat Simulator</strong>] to easily create in-game messages with custom colors and emojis and copy them with one click; consult our detailed [<strong>Farming Guide</strong>] and [<strong>Wanted Missions</strong>] cheat sheet to efficiently locate resources and optimize your strategy. You can save your favorite heroes to a list and share your <strong>Favorites List</strong> with your alliance via a link. The platform fully supports Simplified/Traditional Chinese and English, and includes a Day/Night mode toggle.",
        pageTitle: "Empires & Puzzles Hero Database | Heroplan",
        headerTitle: "Empires & Puzzles Hero Database", poweredBy: "Powered by", driven: "",
        sponsoredBy: "Sponsored by", translatedBy: "Developed by", 
        donationListTitle: "Thanks to all our donors!",
        filterHeroes: "Filter Heroes", standardFilters: "Standard Filters", nameLabel: "Name:", searchLangTitle: 'Select search language',
        currentLangText: '🌐 Current', 'noMatchingResults': 'No matching results', 
        avatarLabel: "Avatar", namePlaceholder: "Enter hero name", costumeTypeLabel: "Costume:",
        starLabel: "Stars:", colorLabel: "Color:", speedLabel: "Speed:", classLabel: "Class:", familyLabel: "Family:",
        sourceLabel: "Origin:", aetherPowerLabel: "Aether Power:", showEventNameLabel: "Show Event Name", filterHeroes: "Filter Heroes",
        filterScopeLabel: "Filter Range:", filterScope_all: "All",
        filterScope_hero: "Hero",
        filterScope_skin: "Costume",
        filterScope_favorites: "Favorites", clearSelection: "Clear Selections", advancedFilters: "Advanced Filters",
        skillTypeSourceLabel: "Type Source:", sourceBoth: "Both", sourceHeroplan: "Heroplan.io", sourceNynaeve: "By Nynaeve", sourceBbcamp: "bbcamp.info",
        skillTypeLabel: "Skill Type:", skillTypePlaceholder: "e.g. buff, ailment, heal", skillTextLabel: "Skill Text:",
        passiveSkillLabel: "Passive Text:", enableSkillQuickSearchLabel: "Quick Skill Search: ", cnSkill_baseLabel: "Skill Base:",
        cnSkill_specialLabel: "Special Effects:",
        cnSkill_buffLabel: "Buffs:",
        cnSkill_debuffLabel: "Debuffs:",
        enableSkillQuickSearchToggle: "Enable", filterBy: "Filter by:", all: "All", hero: "Hero", skin: "Costume", favorites: "Favorites",
        heroAcademyEventLabel: "Hero Academy 10:", oneClickMaxEventLabel: "Hero Coach:", purchaseCostumeEventLabel: "Visiting Outfitter:",
        "soulExchangeEventLabel": "Soul Exchange:",
        "showListBtnLabel": "Show List",
        "soulExchangeModalTitle": "Soul Exchange List",
        filterButtonLabel: "Filter",
        minPower: "Power", minAttack: "Attack", minDefense: "Defense", minHealth: "Health", resetFilters: "Reset Filters",
        hideDonate: "Hide Donate",
        showDonate: "Show Donate",
        exportSettings: "Export Settings",
        importSettings: "Import Settings",
        setting_heroFavorites: "Favorite Heroes",
        setting_savedTeams: "Saved Teams",
        setting_favoriteColors: "Favorite Chat Colors",
        setting_otherSettings: "UI & General Settings",
        exportModalTitle: "Export Settings",
        importModalTitle: "Import Settings",
        exportItems: "Select items to export:",
        importItems: "Select items to import:",
        selectAll: "Select All",
        exportSelected: "Generate Export Code",
        analyzeCode: "Analyze Code",
        importSelected: "Import Selected",
        exportResultTitle: "Your export code (please copy and save it):",
        noDataToExport: "No data available to export.",
        noDataInCode: "No importable data found in the code, or the code is corrupted.",
        importInstructions: "Please paste your previously exported settings code below:",
        importModeOverwrite: "Overwrite Mode: Deletes all current settings and replaces them with the imported ones.",
        importModeAppend: "Append Mode: Keeps existing settings and merges the imported ones (e.g., favorites and saved teams will be merged and deduplicated).",
        importConfirmBtn: "Confirm Import",
        importCancelBtn: "Cancel",
        importSettingsSuccess: (mode, counts) => { // 【新增】
            if (mode === 'overwrite') {
                return 'Settings have been successfully overwritten! The page will now reload to apply changes.';
            }
            // Append mode
            const messages = [];
            if (counts.favorites > 0) messages.push(`Added ${counts.favorites} favorite heroes`);
            if (counts.teams > 0) messages.push(`Added ${counts.teams} teams`);
            if (counts.colors > 0) messages.push(`Added ${counts.colors} favorite colors`);

            if (messages.length === 0) {
                return 'Import complete, no new items were added. The page will now reload.';
            }
            return `Settings successfully appended!\n${messages.join(', ')}.\nThe page will now reload to apply changes.`;
        },
        importError: "Import failed! The code is invalid or corrupted. Please check if the code is complete.",
        saveToFile: "Save to File",
        importFromFile: "Import from File",
        shareFavorites: "Share Favorites", openFavorites: "Open Favorites", shareFavoritesCopied: "List Copied!",
        footerGameName: "Empires & Puzzles", footerPlatform: "Hero Data Platform",
        footerCredit: "© 2025 heroplan.github.io | Unofficial Fan Site",
        resultsCountTextFiltered: (count) => `filtered ${count} Heroes`,
        resultsCountTextUnfiltered: (count) => `${count} Heroes (Included Costumes)`,
        resultsCountTextHeroOnly: (count) => `${count} Heroes (Excluded Costumes)`,
        resultsCountTextCostumeOnly: (count) => `${count} Costumes`,
        favoritesListCount: (count) => `${count} heroes in the favorites list`,
        favoritesListEmpty: "Favorites list is empty. Please add heroes or reset filters",
        resultsReset: "Reset",
        noResults: "No matching heroes found", modalHeroDetails: "ℹ️ Hero Details",
        closeBtnTitle: "Close", modalOrigin: "Origin", modalCoreStats: "📊 Core Stats",
        limitBreakSetting: "Limit Break:",
        noLimitBreak: "None",
        lb1: "🔼LB1",
        lb2: "⏫LB2",
        talentSetting: "Talent:",
        noTalent: "No Talents",
        talent20: "20 Talents",
        talent25: "25 Talents",
        prioritySetting: "Talent Priority:",
        attackPriority: "Attack > Defense > Health",
        defensePriority: "Defense > Health > Attack",
        attackPriority2: "Attack > Health > Defense",
        healthPriority: "Health > Defense > Attack",
        defensePriority2: "Defense > Attack > Health",
        healthPriority2: "Health > Attack > Defense",
        manaPriorityLabel: "Mana Node:",
        manaPriorityToggle: "Prioritize",
        showLbTalentDetailsLabel: "LB/Talent Settings in detail:",
        showLbTalentDetailsToggle: "Show",
        modalTalentSettingsTitle: "Limit Break & Talent Settings",
        customTalentTitle: "Custom Talents",
        talentTreeTitle: "Class Talent Tree", modalSettings: "Settings", defaultStatSettingsTitle: "LB Talent Settings", toggleCollapse: "Click to collapse/expand", modalSkillDetails: "📖 Skill Details",
        modalSkillName: "📄 Name:", modalSpeed: "⌛ Speed:", modalSkillType: "🏷️ Skill Tags:",
        modalSpecialSkill: "✨ Skill Effects:", modalPassiveSkill: "🧿 Passive Skill:",
        modalFamilyBonus: (family) => `👪 Family Bonuses (${family}):`, modalSkin: "Costume:", none: "None", detailsCloseBtn: "Close",
        shareButtonTitle: "Share", favoriteButtonTitle: "Favorite", favColumnHeader: "☆",
        favHeaderTitle: "Favorite/Unfavorite All",
        confirmFavoriteAll: "Are you sure you want to favorite all heroes in the current list?",
        confirmUnfavoriteAll: "Are you sure you want to unfavorite all heroes in the current list?",
        filterHelpTitle: "Advanced Filter Syntax",
        filterHelpIntro: "In the 'Skill Text/Passive Text' fields, you can use these operators for complex queries:",
        filterHelpOr: "<li><strong>| (OR):</strong> Finds heroes with any of the specified keywords. E.g., <code>heal|revive</code> finds heroes with 'heal' or 'revive'.</li>",
        filterHelpAnd: "<li><strong>Space (AND):</strong> Finds heroes that must contain all keywords. E.g., <code>attack up</code> finds heroes with both 'attack' and 'up'.</li>",
        filterHelpNot: "<li><strong>! (NOT):</strong> Excludes heroes with a specific keyword. E.g., <code>!heal</code> finds all heroes without 'heal' in their skills.</li>",
        filterHelpGroup: "<li><strong>() (Grouping/Single-Line Match):</strong> Use parentheses for complex grouping and to <strong style='color: var(--md-sys-color-error);'>force matching within a single skill line</strong>. E.g., <code>(resist heal)</code> will precisely find heroes where a <strong style='color: var(--md-sys-color-error);'>single line</strong> of their skill description contains both 'resist' and 'heal'.</li>",
        filterHelpExact: "<li><strong>[] (Exact Match):</strong> Use square brackets to <strong style='color: var(--md-sys-color-error);'>force an exact match on a single skill type line</strong>. E.g., <code>[Cleanse]</code> will find heroes with the exact type 'Cleanse', and not 'Cleansers'.</li>",
        filterHelpExample: "<li><strong>Combined Example:</strong> <code>((immune|reflect) buff)</code> finds heroes who provide an immunity or reflection buff (and all conditions must be met in the same line).</li>",
        skillTypeHelpTitle: "Skill Type Source Explanation",
        skillTypeHelpContent: `<p>You can choose different sources for skill category tags to filter by:</p><ul><li><strong>Heroplan.io:</strong> Data from the <a href="https://heroplan.io/" target="_blank" rel="noopener noreferrer">Heroplan.io</a> website.</li><li><strong>By Nynaeve:</strong> Data from <a href="http://www.theravenscave.com/" target="_blank" rel="noopener noreferrer">www.theravenscave.com</a>, supplemented by AI and manually reviewed. (Tag definitions include the skill itself, as well as guaranteed-to-trigger passives and family bonuses).</li><li><strong>bbcamp.info:</strong> Tag definitions reference <a href="https://bbcamp.info" target="_blank" rel="noopener noreferrer">bbcamp.info</a>, revised by AI and manually reviewed. (Focuses only on the effect of the skill itself and ignores the effect of Elemental Links, which can be filtered in the standard filters).</li><li><strong>All:</strong> Searches tags from all of the above sources simultaneously.</li></ul><p>For detailed category definitions, please refer to the source websites.</p>`,
        noFavoritesToShare: "No favorites to share.",
        copyLinkFailed: "Failed to copy link. Please try copying it manually.",
        wantedMissionTableTitle: "Wanted Mission Table",
        farmingGuideTableTitle: "Farming Locations Guide",
        questHeaderDaily: "Daily",
        questHeaderRed: "Red",
        questHeaderGreen: "Green",
        questHeaderBlue: "Blue",
        questHeaderPurple: "Purple",
        questHeaderYellow: "Yellow",
        toggleThemeTitle: "Toggle day/night mode",
        toggleLanguageTitle: "Toggle language",
        showLotterySimulatorTitle: "Summon Simulator",
        showTeamSimulatorTitle: "Team Simulator",
        showChatSimulatorTitle: "Chat Simulator",
        showFarmingGuideTitle: "Farming Guide",
        showWantedMissionTitle: "Show Wanted Mission Table",
        openFiltersTitle: "Open Filters",
        calendarTitle: "View Event Calendar",
        filterSyntaxTitle: "Filter Syntax Help",
        skillTypeSourceHelpTitle: "Skill Type Source Help",
        lotterySimulatorTitle: "Lottery Simulator",
        returnToList: "Return",
        teamDisplayTitle: "Team Configuration",
        noTeamTags: "No skill tags in the team",
        saveTeamBtn: "Save Team",
        shareTeamListBtn: "Share List",
        savedTeamsTitle: "Saved Teams",
        promptTeamName: "Enter a name for your team:",
        teamNameRequired: "Team name cannot be empty.",
        noHeroesInTeam: "No heroes in the team to save.",
        removeTeamBtnTitle: "Remove this team",
        noSavedTeams: "No saved teams.",
        confirmRemoveTeam: (name) => `Are you sure you want to remove the team "${name}"?`,
        shareTeamListCopied: "Link copied!",
        noTeamsToShare: "No teams to share.",
        clearTeamBtn: "Clear Team",
        confirmClearTeam: "Are you sure you want to clear the current team? All unsaved changes will be lost.",
        importSuccess: (teamName) => `Team "${teamName}" imported successfully!`,
        importConfirmOverwrite: (teamName) => `Team "${teamName}" already exists. Overwrite it?`,
        importTeamBtn: "Import",
        importEnterNewName: (teamName) => `Team "${teamName}" already exists. Please enter a new name to import:`,
        importedBtn: "Imported",
        teamImportedBtn: "Imported",
        sharedTeamsTitle: "Shared Teams",
        myTeamsTab: "My Teams",
        sharedTeamsTab: "Shared Teams",
        summaryTagsTitle: "Skill Tags Summary",
        // --- Chat Simulator New Texts ---
        showChatSimulatorTitle: "Chat Simulator",
        chatSimulatorTitle: "Chat Simulator",
        chatPanelTitleColors: "Select Color",
        chatFavoriteColorBtn: "⭐",
        chatFavoriteColorsTitle: "Favorite Colors",
        chatPanelTitleEmojis: "Select Emojis",
        chatPanelTitleIO: "Input & Preview",
        chatInsertColorBtn: "Add",
        chatCopyBtn: "Copy Content",
        chatCopied: "Copied!",
        talentTerms: {
            '攻击': 'Attack',
            '防御': 'Defense',
            '生命': 'Health',
            '法力': 'Mana',
            '治疗': 'Healing',
            '暴击': 'Critical',
            '游侠天赋': 'Ranger Talent', '战士天赋': 'Fighter Talent', '圣骑天赋': 'Paladin Talent',
            '野蛮人天赋': 'Barbarian Talent', '牧师天赋': 'Cleric Talent', '德鲁伊天赋': 'Druid Talent',
            '僧侣天赋': 'Monk Talent', '盗贼天赋': 'Rogue Talent', '术士天赋': 'Sorcerer Talent', '巫师天赋': 'Wizard Talent',
            '游侠终极天赋': 'Ranger Ultimate Talent', '战士终极天赋': 'Fighter Ultimate Talent', '圣骑士终极天赋': 'Paladin Ultimate Talent',
            '野蛮人终极天赋': 'Barbarian Ultimate Talent', '牧师终极天赋': 'Cleric Ultimate Talent', '德鲁伊终极天赋': 'Druid Ultimate Talent',
            '僧侣终极天赋': 'Monk Ultimate Talent', '盗贼终极天赋': 'Rogue Ultimate Talent', '术士终极天赋': 'Sorcerer Ultimate Talent', '巫师终极天赋': 'Wizard Ultimate Talent',
        },
        bonusAndCostTitle: "Bonuses & Costs",
        attackBonusLabel: "Attack:",
        defenseBonusLabel: "Defense:",
        healthBonusLabel: "Health:",
        manaBonusLabel: "Mana:",
        healingBonusLabel: "Healing:",
        critBonusLabel: "Critical:",
        noBonusLabel: "No attribute bonuses gained",
        emblemCostLabel: "Emblems:",
        foodCostLabel: "Food:",
        ironCostLabel: "Iron:",
        masterEmblemCostLabel: "Master Emblems:",
        lbTalentHelpTitle: "Limit Break & Talent Settings Help",
        lbTalentHelpLine1: "Data for post-limit break stats are from <a href='https://bbcamp.info' target='_blank' rel='noopener noreferrer'>https://bbcamp.info</a>",
        lbTalentHelpLine2: "Mana Priority gives mana nodes the highest priority, ensuring they are always selected in the talent path.",
        viewLatest: 'View Latest',
        modalAttributeTalentBtn: 'Stats/Talents',
        modalSkillTagsHeader: '📖 Skill Details',
        modalSkillDetailsBtn: 'Skill Tags',
        modalSkillEffectBtn: 'Skill Effects',
        modalPassiveBtn: 'Passive Skills',
        modalFamilyBonusBtn: 'Family Bonuses',
        // --- 抽奖模拟器新增文本 ---
        lotterySimulatorTitle: "Lottery Simulator",
        summonOnce: "Summon",
        summonTen: "Summon x10",
        summonThirty: "Summon x30",
        confirmClearHistory: "Are you sure you want to clear all summon history?",
        "toggleShowAllHistoryLabel": "Show All History",
        "confirmClearCurrentHistory": "Are you sure you want to clear the summon history for the current event?",
        "summonHistoryTitleCurrent": (poolName, count) => `${poolName} Summon History (Total ${count} pulls)`,
        "summonHistoryTitleAll": "All Summon History",
        "calculatedProbabilitiesTitle": "Calculated Probabilities For This Event Summon",
        noSummonHistory: "No summon history",
        clearHistoryBtn: "Clear",
        summonResultsTitle: "Summon Results",
        skipAnimation: "Skip Animation",
        lotteryTabActivity: "Events",
        lotteryTabSummon: "Summon",
        summonHistoryTitle: "Summon History",
        lotteryTabHistory: "History",
        probabilityInfoTitle: "Probability Details",
        StageGuideTitle: "Stage Guide",
        probabilityInfoIntro: "Summon probabilities for the current pool:",
        lottery_bucket_translations: {
            // Summon details bucket translations
            "heroes_ex_s1_3": "Non-Classic Heroes (3*)",
            "heroes_ex_s1_4": "Non-Classic Heroes (4*)",
            "heroes_ex_s1_5": "Non-Classic Heroes (non-featured) (5*)",
            "heroes_s1_3": "Classic Heroes (3*)",
            "heroes_s1_4": "Classic Heroes (4*)",
            "heroes_s1_5": "Classic Heroes (5*)",
            "heroes_event_3": "Event Heroes (3*)",
            "heroes_event_4": "Event Heroes (4*)",
            "heroes_event_5": "Event Heroes (non-featured) (5*)",
            "heroes_listed_3": "Listed Heroes (3*)",
            "heroes_listed_4": "Listed Heroes (4*)",
            "heroes_listed_5": "Listed Heroes (non-featured) (5*)",
            "heroes_extraAssociatedFamilies_3": "Extra Family Heroes (3*)",
            "heroes_extraAssociatedFamilies_4": "Extra Family Heroes (4*)",
            "heroes_extraAssociatedFamilies_5": "Extra Family Heroes (5*)",
            "featuredHero": "Featured Hero (5*)",
            "trainer_3": "Trainer (3*)",
            "trainer_4": "Trainer (4*)",
        },
        "lottery_bonus_translations": {
            "bonusProbabilityTitle": "Bonus Odds",
            "hotm": "HOTM Rate",
            "MysteryHero": "Mystery Hero Rate",
            "LegendsSummonMysteryHero": "Legends Summon Mystery Hero Rate",
            "additionalDrawWeights": "Total Draw Rates",
            "bonusLegendaryHeroChancePerMil": "Bonus Rate",
            "bonusLegendaryHeroType": "Bonus Hero Type",
            "bonusLegendaryProbabilityTitle": "Bonus Legendary Hero",
            "bonusLegendaryHeroPullAmount": "Bonus Pulls"
        },
        "lottery_bonus_values": {
            "eventHeroesOnly": "Event Heroes Only",
            "NonClassicHero": "Non-Classic Heroes"
        },
        "selectElementTitle": "Select Element",
        "superElementalExclusionNotice": (days) => `* Does not include non-event family heroes released within ${days} days`,
        "noMysteryBonusNotice": "This summon does not include a chance for a bonus draw the Secret Hero.",
        "includesTrainerNotice": "* This pool includes Trainer",
        "summonSummaryOkBtn": "OK",
        "playMode_full": "Play Full Animation", 
        "playMode_skip": "Skip Animation, Show Results", 
        "playMode_silent": "Directly to History, No Pop-up", 
        "muteSound": "Mute",
        "unmuteSound": "Unmute",
        "featuredHeroRequired": 'Please use the ⬆️ icon in the table below to set at least one featured hero before summoning.',
        "mustSelect5StarHero": "Please select a 5-star hero.",
        "featuredSlotsFull": "All featured hero slots are full. You can double-click a featured hero's avatar to remove it.",
        "totalHeroesCountText": (count) => `(Total ${count})`,
        "latestHeroAgeNotice": (days) => `* Only includes heroes and costumes released within ${days} days`,
        "w3kLimitedPoolTitle": "View 3K Limited Pool",
        "showRedeemCodesTitle": "View Redeem Codes",
        "redeemCodesModalTitle": "Available Redeem Codes",
        "redeemBtn": 'Redeem',
        highlightSkillTermsLabel: "Highlight Skill Terms:",
        highlightSkillTermsToggle: "Enable",
        showSkillTypesInDetailsLabel: "Skill types in details:",
        showSkillTypesInTeamLabel: "Skill types in team:",
        showSkillTypesToggle: "Enable",
        showCircleRayLabel: "Show rays in Hero Avatar:",
        showCircleRayToggle: "Enable",
    }
}; 